# Generated by Django 5.0 on 2023-12-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=170)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('anio', models.PositiveIntegerField()),
                ('km', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transmision', models.CharField(max_length=20)),
                ('estado', models.CharField(default='disponible', max_length=20)),
                ('imagen', models.ImageField(upload_to='auto_images/')),
                ('marca_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.marcamodelo')),
            ],
        ),
    ]
